username=ashwin.d
password=Admin!123
baseUrl=https://192.168.100.135:32222/
homePageUrl=https://192.168.100.135:32222/


# ******* 100.12 Server **********
#baseUrl=https://qa.onprem.icedq.com/
#homePageUrl=https://qa.onprem.icedq.com/


# ****** 100.135 Server *********
#baseUrl=https://192.168.100.135:32222/
#homePageUrl=https://192.168.100.135:32222/


# ****** 100.35 Server *********
#baseUrl=https://192.168.100.35:32222
#homePageUrl=https://192.168.100.35:32222

# E-mail server login details.
MailUserName=icedq-svc@toranainc.com
MailPassword=IceDQ123@svc
EmailHost=smtp.office365.com
MailPort=587
MailTo=ashwin.d@toranainc.com
MailCC=ashwin.d@toranainc.com

# vipul.s@toranainc.com
# dhawal.t@toranainc.com
# arijit.k@icedq.ai