username=ashwin.d
password=Admin@1234
baseUrl=https://qa.onprem.icedq.com/
homePageUrl=https://qa.onprem.icedq.com/


# E-mail server login details.
MailUserName=icedq-svc@toranainc.com
MailPassword=IceDQ123@svc
EmailHost=smtp.office365.com
MailPort=587
MailTo=ashwin.d@toranainc.com
MailCC=ashwin.d@toranainc.com

# vipul.s@toranainc.com