login.username=id~~username
login.password=name~~password
login.submit=xpath~~//input[@type='submit']
logout.profileMenuItem=xpath~~//*[@role='menuitem']
logout.button=xpath~~//*[@aria-label='Logout']
#Loader is displayed
loaderIsDisplayed=xpath~~//div[@id="sp-container"]//div[@class='e-spinner-pane e-spin-show']//div