// Test Generator
home.testgenerator=xpath~~//button[.//h2[text()='Test Generator']]
// Select the checksum rule wizard
wizard.checksumRule=xpath~~//h6[text()='Checksum']
// Search Template field
wizard.searchfield.tempatename=xpath~~//input[contains(@placeholder,'Search template')]
// Enter data on the search Template field
wizard.searchfield.enter.tempatename=xpath~~//input[contains(@placeholder,'Search template')]

// Click on the search button icon on the template search field.
wizard.searchfield.searchButtonIcon=xpath~~//*[@title='Search']

// Select the existing dynamic checksum template.
wizard.existing.dymanic.template=xpath~~//td[@class='e-rowcell e-templatecell e-lastrowcell']/span[@class='dib'][contains(., 'Compare Record Counts - Dynamic SQL')]

// Click on the workspace dropdown field
wizard.workspace.dropdown=xpath~~//span[./input[contains(@class, 'e-input')]]

// Select the workspace name from the dropdown
select.Workspace=xpath~~//span[./input[contains(@class, 'e-input')]]

// Select the searched workspace
select.searchedWorspace=xpath~~//input[@class='e-input-filter e-input e-lib e-keyboard']

// Click on the folder dropdown field
wizard.folder.dropdown=xpath~~//button[@aria-label='Folder']//parent::div

// Search folder name
wizard.search.folderName=xpath~~//div[@class='dropdown__search-group e-input-group']/input[@id='searchFolder']

// Select the searched folder
select.searchedfolder=xpath~~//button[@aria-label="Select folder"]

// 
// Loader is displayed
loderIsDisplayed=xpath~~//div[@id="sp-container"]//div[@class='e-spinner-pane e-spin-show']//div
// Source schema dropdown
source.schema.dropdown=xpath~~(//div[contains(text(),'Source Dataset')]/parent::form//following::ejs-dropdownlist[@placeholder='Choose Schema']//span[@formcontrolname='schema'])[1]
target.schema.dropdown=xpath~~(//div[contains(text(),'Source Dataset')]/parent::form//following::ejs-dropdownlist[@placeholder='Choose Schema']//span[@formcontrolname='schema'])[2]