// Test Generator module
home.testgenerator = xpath~~//button[.//h2[text()='Test Generator']]

// Template sub-module
template.subModule = xpath~~//*[contains(text(),'Template')]

// Search box field - search template name
searchField.searchTemplate = xpath~~//*[@placeholder='Search template']

// Search box field - search icon
searchButtonIcon.searchTemplate = xpath~~//*[@placeholder='Search template']/following-sibling::span[2]

// Select the search item from the list
searchItem.fromList = xpath~~//*[@id='templateGrid_content_table']/tbody/tr/td[3]/a

// Copy button
copyButton = xpath~~//*[@aria-label='Copy']

// New Template button
newTemplateButton = xpath~~//*[contains(normalize-space(text()), 'New Template')]

// Account field drop down
accountName = xpath~~//*[@formcontrolname='accountId']/span[@aria-label='dropdownlist']

// Account name list
accountNameList = xpath~~//*[@aria-label='listbox']/li

//Rule type field dropdown
ruleType = xpath~~//*[@formcontrolname='ruleType']/span[@aria-label='dropdownlist']

// Rule type list
ruleTypeList = xpath~~//*[@aria-label='listbox']/li

// Name field
name = xpath~~//input[@placeholder='Enter name']

// Description field
description = xpath~~//textarea[@placeholder='Enter description (optional)']

// JSON field
json = xpath~~//*[contains(@class,'ace_editor')]

// Click on the save button
saveButton = xpath~~//*[contains(normalize-space(text()), 'Save')]