// Test Generator
home.testgenerator=xpath~~//button[.//h2[text()='Test Generator']]

// Select the checksum rule wizard
wizard.checksumRule=xpath~~//h6[text()='Checksum']

// Select the recon rule wizard
wizard.reconRule=xpath~~//h6[text()='Recon']

// Select the validation rule wizard
wizard.validationRule=xpath~~//h6[text()='Validation']

// Select the pushdown rule wizard
wizard.pushdownRule=xpath~~//h6[text()='Pushdown']

// Search Template field
wizard.searchfield.tempatename=xpath~~//input[contains(@placeholder,'Search template')]

// Enter data on the search Template field
wizard.searchfield.enter.tempatename=xpath~~//input[contains(@placeholder,'Search template')]

// Click on the search button icon on the template search field.
wizard.searchfield.searchButtonIcon=xpath~~//*[@title='Search']

// Select the existing dynamic checksum template.
wizard.existing.dymanic.template=xpath~~//div[@class='e-gridcontent']//tbody[@role='rowgroup']/tr[1]

// Click on the workspace dropdown field
wizard.workspace.dropdown=xpath~~//span[./input[contains(@class, 'e-input')]]

// Select the workspace name from the dropdown
select.Workspace=xpath~~//span[./input[contains(@class, 'e-input')]]

// Select the searched workspace
select.searchedWorspace=xpath~~//input[@class='e-input-filter e-input e-lib e-keyboard']

// Click on the folder dropdown field
wizard.folder.dropdown=xpath~~//button[@aria-label='Folder']//parent::div

// Search folder name
wizard.search.folderName=xpath~~//div[@class='dropdown__search-group e-input-group']/input[@id='searchFolder']

// Select the searched folder
select.searchedfolder=xpath~~//button[@aria-label="Select folder"]

// Click on the next button of the metadataNextbtn
wizard.click.nextButton.workspaceNextbtn=xpath~~//button[@id='workspaceNextbtn']

// Click on the next button of the gotoWorkspaceNextbtn
wizard.click.nextButton.metadataNextbtn=xpath~~//button[@id='metadataNextbtn']

// Click on the next button of the checkNextbtn
wizard.click.nextButton.checkNextbtn=xpath~~//button[@id='checkNextbtn']

// Click on the next button of the notificationNextbtn
wizard.click.nextButton.notificationNextbtn=xpath~~//button[@id='notificationNextbtn']

// Click on the source dataset of connection type dropdown
wizard.click.sourceConnectionTypeDropdown=xpath~~(//div[contains(text(),'Source Dataset')]//parent::form//following::ejs-dropdownlist[@placeholder='Select connection type']//span[@formcontrolname='connectionType'])[1]

// Click on the source dataset of connection dropdown
wizard.click.sourceConnectionDropdown=xpath~~(//div[contains(text(),'Source Dataset')]//parent::form//following::ejs-dropdownlist[@placeholder='Select connection']//span[@formcontrolname='connectionId'])[1]

// Enter source connection name
wizard.source.connection.input = xpath~~//*[@placeholder='Select connection']/following::div[contains(@class,'e-popup')]//input[@type='text']

// Click on the Source schema dropdown
wizard.source.schema.dropdown=xpath~~(//div[contains(text(),'Source Dataset')]/parent::form//following::ejs-dropdownlist[@placeholder='Choose Schema']//span[@formcontrolname='schema'])[1]

// Enter source schema name
wizard.source.schema.input = xpath~~//ejs-dropdownlist[@placeholder='Choose Schema']/following::div[contains(@class,'e-popup')]//input[@type='text']


// Click on the target dataset of connection type dropdown
wizard.click.targetConnectionTypeDropdown=xpath~~(//div[contains(text(),'Source Dataset')]//parent::form//following::ejs-dropdownlist[@placeholder='Select connection type']//span[@formcontrolname='connectionType'])[2]

// Click on the target dataset of connection dropdown
wizard.click.targetConnectionDropdown=xpath~~(//div[contains(text(),'Source Dataset')]//parent::form//following::ejs-dropdownlist[@placeholder='Select connection']//span[@formcontrolname='connectionId'])[2]

// Enter target connection name
wizard.target.connection.input = xpath~~//*[@placeholder='Select connection']/following::div[contains(@class,'e-popup')]//input[@type='text']

// Click on the Source schema dropdown
wizard.target.schema.dropdown=xpath~~(//div[contains(text(),'Source Dataset')]/parent::form//following::ejs-dropdownlist[@placeholder='Choose Schema']//span[@formcontrolname='schema'])[2]

// Enter target schema name
wizard.target.schema.input = xpath~~//ejs-dropdownlist[@placeholder='Choose Schema']/following::div[contains(@class,'e-popup')]//input[@type='text']

// Click on the next button of the datasetNextbtn
wizard.click.nextButton.datasetNextbtn=xpath~~//button[@id='datasetNextbtn']

// Available Table
availableTable.click = xpath~~//input[@placeholder='Search available table']

// Select the table from the available table list
availableTable.select.table =xpath~~//ul//li[@id='staff']

// Click on the moveto button
availableTable.moveto.click = xpath~~//button[@aria-label='Move To']

// Click on the next button of the SelettableNextbtn
availableTable.click.nextButton.SelettableNextbtn=xpath~~//div[@id='e-content-element_6']//button[normalize-space()='Next']

// Click on the generate button
generateButton.click = xpath~~//button[@id='reviewNextbtn']

// Click on the go to preview button
goToPreviewButton.click = xpath~~//button[normalize-space()= 'Go To Preview']

// Select the generated entity for the publish
publishEntity.select = xpath~~//tbody[@role='rowgroup']/tr/td/div/input[@type='checkbox']/following-sibling::span[1]

// Click on the publish button 
published.click =xpath~~//button[@title='Publish']

// Click on the go to publish button
goToPublishButton.click = xpath~~//*[@id='publishLogMessageSidebar']//button[contains(text(),'Go To Publish')]

// Click on the publish entity hyperlink
publishRuleHyperlink.click = xpath~~//*[@id="publishGrid_content_table"]/tbody/tr[1]/td[1]/a



// Loader is displayed
loderIsDisplayed=xpath~~//div[@id="sp-container"]//div[@class='e-spinner-pane e-spin-show']//div

target.schema.dropdown=xpath~~(//div[contains(text(),'Source Dataset')]/parent::form//following::ejs-dropdownlist[@placeholder='Choose Schema']//span[@formcontrolname='schema'])[2]