#Test Generator
home.testgenerator = xpath~~//button[.//h2[text()='Test Generator']]

#Select the checksum rule wizard
wizard.checksumRule = xpath~~//h6[text()='Checksum']

#Select the recon rule wizard
wizard.reconRule=xpath~~//h6[text()='Recon']

#Select the validation rule wizard
wizard.validationRule=xpath~~//h6[text()='Validation']

#Select the pushdown rule wizard
wizard.pushdownRule=xpath~~//h6[text()='Pushdown']

#Click on the account dropdown field
wizard.account.dropdown=xpath~~//*[@placeholder='Select account']/span

#Enter the account name
wizard.account.searchfield=xpath~~//*[@role='dialog']/span/span/input

#Click on the next button of the Select account
wizard.account.next.button=xpath~~//button[@id='accountNextbtn']

#Search Template field
wizard.searchfield.tempatename=xpath~~//input[contains(@placeholder,'Search template')]

#Enter data on the search Template field
wizard.searchfield.enter.tempatename=xpath~~//input[contains(@placeholder,'Search template')]

#Click on the search button icon on the template search field.
wizard.searchfield.searchButtonIcon=xpath~~//*[@title='Search']

#Select the existing dynamic checksum template.
wizard.existing.dymanic.template=xpath~~//div[@class='e-gridcontent']//tbody[@role='rowgroup']/tr[1]

#Click on the workspace dropdown field
wizard.workspace.dropdown=xpath~~//*[@placeholder='Select workspace']/span

#Search workspace name
select.Workspace=xpath~~//*[@role='dialog']/span/span/input

#Select the searched workspace
select.searchedWorkspace=xpath~~//input[@class='e-input-filter e-input e-lib e-keyboard']

#Click on the folder dropdown field
wizard.folder.dropdown=xpath~~//button[@aria-label='Folder']/parent::div

#Search folder name
wizard.search.folderName=xpath~~//*[@placeholder='Search folder']

#Search icon
wizard.folderName.search.icon=xpath~~//div[@id='pathtree']//span[@title='Search']

#Click the searched folder item from the list
wizard.folderName.searched=xpath~~//div[contains(@class, 'e-text-content')]

#Click right tick icon to select the folder
wizard.folderName.rightTick.icon=xpath~~//span[@class='e-icons e-check']//parent::button

#Select the searched folder
select.searchedfolder=xpath~~//button[@aria-label="Select folder"]

#Click on the next button of the metadataNextbtn
wizard.click.nextButton.workspaceNextbtn=xpath~~//button[@id='workspaceNextbtn']

#Click on the next button of the gotoWorkspaceNextbtn
wizard.click.nextButton.metadataNextbtn=xpath~~//button[@id='metadataNextbtn']

#Click on the next button of the checkNextbtn
wizard.click.nextButton.checkNextbtn=xpath~~//button[@id='checkNextbtn']

#Click on the next button of the notificationNextbtn
wizard.click.nextButton.notificationNextbtn=xpath~~//button[@id='notificationNextbtn']

#Click on the Database connection type
wizard.Database.connectionType = xpath~~//li[text()='Database']

#Click on the Cloud Data Warehouse connection type
wizard.CloudDataWarehouse.connectionType = xpath~~//li[text()='Cloud Data Warehouse']

#Click on the File connection type
wizard.File.connectionType = xpath~~//li[text()='File']


#Click on the source dataset of connection type dropdown
wizard.click.sourceConnectionTypeDropdown=xpath~~(//div[contains(text(),'Source Dataset')]//parent::form//following::ejs-dropdownlist[@placeholder='Select connection type']//span[@formcontrolname='connectionType'])[1]

#Click on the source dataset of connection dropdown
wizard.click.sourceConnectionDropdown=xpath~~(//div[contains(text(),'Source Dataset')]//parent::form//following::ejs-dropdownlist[@placeholder='Select connection']//span[@formcontrolname='connectionId'])[1]

#Enter source connection name
wizard.source.connection.input = xpath~~//*[@placeholder='Select connection']/following::div[contains(@class,'e-popup')]//input[@type='text']

#Click on the Source schema dropdown
wizard.source.schema.dropdown = xpath~~(//div[contains(text(),'Source Dataset')]/parent::form//following::ejs-dropdownlist[@placeholder='Choose Schema']//span[@formcontrolname='schema'])[1]

#Enter source schema name
wizard.source.schema.input = xpath~~//ejs-dropdownlist[@placeholder='Choose Schema']/following::div[contains(@class,'e-popup')]//input[@type='text']


#Click on the target dataset of connection type dropdown
wizard.click.targetConnectionTypeDropdown=xpath~~(//div[contains(text(),'Source Dataset')]//parent::form//following::ejs-dropdownlist[@placeholder='Select connection type']//span[@formcontrolname='connectionType'])[2]

#Click on the target dataset of connection dropdown
wizard.click.targetConnectionDropdown=xpath~~(//div[contains(text(),'Source Dataset')]//parent::form//following::ejs-dropdownlist[@placeholder='Select connection']//span[@formcontrolname='connectionId'])[2]

#Enter target connection name
wizard.target.connection.input = xpath~~//*[@placeholder='Select connection']/following::div[contains(@class,'e-popup')]//input[@type='text']

#Click on the Source schema dropdown
wizard.target.schema.dropdown=xpath~~(//div[contains(text(),'Source Dataset')]/parent::form//following::ejs-dropdownlist[@placeholder='Choose Schema']//span[@formcontrolname='schema'])[2]

#Enter target schema name
wizard.target.schema.input = xpath~~//ejs-dropdownlist[@placeholder='Choose Schema']/following::div[contains(@class,'e-popup')]//input[@type='text']

#Click on the next button of the datasetNextbtn
wizard.click.nextButton.datasetNextbtn=xpath~~//button[@id='datasetNextbtn']

#Click on the next button of the importsqlNextbtn
wizard.click.nextButton.importSQLNextbtn = xpath~~//*[@id='e-content-element_6']/div/div[1]/button[2]

#Available Table
availableTable.click = xpath~~//input[@placeholder='Search available table']

#Select the table from the available table list
availableTable.select.table =xpath~~//ul//li[@id='staff']

#Click on the moveto button
availableTable.moveto.click = xpath~~//button[@aria-label='Move To']

#Click on the next button of the Select table Nextbtn
availableTable.click.nextButton.SelecttableNextbtn=xpath~~//button[contains(@id,'templateNextbtn')]

#Click on the generate button
generateButton.click = xpath~~//button[@id='reviewNextbtn']

#Click on the go to preview button
goToPreviewButton.click = xpath~~//button[normalize-space()= 'Go To Preview']

#Select the generated entity for the publish
publishEntity.select = xpath~~//tbody[@role='rowgroup']/tr/td/div/input[@type='checkbox']/following-sibling::span[1]

#Click on the publish button 
published.click =xpath~~//button[@title='Publish']

#Click on the go to publish button
goToPublishButton.click = xpath~~//*[@id='publishLogMessageSidebar']//button[contains(text(),'Go To Publish')]

#Click on the publish entity hyperlink
publishRuleHyperlink.click = xpath~~//*[@id="publishGrid_content_table"]/tbody/tr[1]/td[1]/a

#Loader is displayed
loderIsDisplayed=xpath~~//div[@id="sp-container"]//div[@class='e-spinner-pane e-spin-show']//div

#Target schema dropdown fields
target.schema.dropdown=xpath~~(//div[contains(text(),'Target Dataset')]/parent::form//following::ejs-dropdownlist[@placeholder='Choose Schema']//span[@formcontrolname='schema'])[1]

#Use mata data cache button
source.metaDataCache=xpath~~//*[@id='e-content-element_5']/div/div[2]/div[1]/form/div[2]/div[3]/div/ejs-checkbox/label/span[2]

#Check on the Source Database Dropdown
source.database.dropdown=xpath~~(//div[contains(text(),'Source Dataset')]/parent::form//following::ejs-dropdownlist[@placeholder='Choose Database']//span[@formcontrolname='database'])[1]

#Enter source Database name
source.database.input=xpath~~//*[@placeholder='Select connection']/following::div[contains(@class,'e-popup')]//input[@type='text']

#Check on the Target Database Dropdown
target.database.dropdown=xpath~~(//div[contains(text(),'Target Dataset')]/parent::form//following::ejs-dropdownlist[@placeholder='Choose Database']//span[@formcontrolname='database'])[1]

#Enter target Database name
target.database.input=xpath~~//*[@placeholder='Select connection']/following::div[contains(@class,'e-popup')]//input[@type='text']

#Click on the publish button
workflow.publish.button=xpath~~//*[@id='publish_item']

#Click on the workflow publish option
workflow.publish.option=xpath~~//*[@id='publish_item-popup']/ul/li[contains(text(),'Workflow')]

#Click on the add to existing workflow option
workflow.addToExistingWorkflow.radio.button=xpath~~//*[contains(text(),'Add to Existing Workflow')]

#Click on the folder dropdown
workflow.folder.dropdown=xpath~~//*[@id='publishRW']/div[2]/div[1]/div[2]/div[2]/div/div[1]

#Click on the Searched folder name
workflow.folder.search.field=xpath~~//*[@placeholder='Search folder']

#Select the searched folder
workflow.folder.name=xpath~~//*[@id='ruleListRighttreeView_active']/div[2]/span/div

#Click on the select button of the folder
workflow.folder.select.button=xpath~~//*[@id='ruleListRighttreeView_active']/div[2]/span/div/div/button[1]/span

#Click on the workflow dorp down
workflow.dropdown.field=xpath~~//*[@placeholder='Workflow Name']/span

#Enter the workflow name
workflow.create.button=xpath~~//*[@aria-label='workflowDropdown']/span/span/input

#Click on the Add button
workflow.add.button=xpath~~//button[contains(normalize-space(text()), 'Add')]

